Package:
 sources:
  - git:
     src: 'https://github.com/projectatomic/docker.git'
     commit_id: 'ae7d637fcad9be396e75af430405446f9e6ab099'
  - git:
     src: 'https://github.com/projectatomic/docker-storage-setup.git'
     commit_id: 'c9faba1908b8e77f7c7c443f26e3b3cb1450d1a0'
     archive: 'docker-storage-setup-c9faba1908b8e77f7c7c443f26e3b3cb1450d1a0'
  - git:
     src: 'https://github.com/projectatomic/docker-novolume-plugin.git'
     commit_id: 'c5212546ab01b4b7b62caba888d298ab63f53984'
     archive: 'docker-novolume-plugin-c5212546ab01b4b7b62caba888d298ab63f53984'
  - git:
     src: 'https://github.com/docker/v1.10-migrator.git'
     commit_id: '994c35cbf7ae094d4cb1230b85631ecedd77b0d8'
     archive: 'v1.10-migrator-994c35cbf7ae094d4cb1230b85631ecedd77b0d8'
  - git:
     src: 'https://github.com/projectatomic/runc.git'
     commit_id: '3819cd61f5263275788f7279fe9d2bc13f086aa6'
     archive: 'runc-3819cd61f5263275788f7279fe9d2bc13f086aa6'
  - git:
     src: 'https://github.com/projectatomic/containerd.git'
     commit_id: '9f4539363c8edc73ae7bdd6ca30f83fc365bf9e1'
     archive: 'containerd-9f4539363c8edc73ae7bdd6ca30f83fc365bf9e1'
 files:
  CentOS:
   '7':
    build_dependencies:
     - golang
    install_dependencies:
     - container-selinux
     - skopeo
